# Auto-generated by start_demo.sh - DO NOT EDIT MANUALLY
# This file is regenerated each time start_demo.sh runs with the current ngrok URL

fhir_server_url = "https://asia-bosker-renna.ngrok-free.dev/fhir"
